[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "applyllm"
version = "0.0.2.dev0"
authors = [
    { name="Yingding Wang", email="yingdingwang@yahoo.de" },
]
description = "a utility package to apply opensource LLM in local cuda environment"
requires-python = ">=3.8"
classifiers = [
   "Programming Language :: Python :: 3",
   "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/yingding/applyllm"
Issues = "https://github.com/yingding/applyllm/issues"

[tool.setuptools.packages]
find = {}